version: '3'

services:
  hugo:
    image: jakejarvis/hugo-extended:latest
    ports:
      - 1313:1313
    volumes:
      - ./:/src
    working_dir: /src
    command: server --buildDrafts --buildFuture --bind 0.0.0.0

# version: "3.3"

# services:

#   site:
#     image: docsy/docsy-example
#     build:
#       context: .
#     command: server
#     ports:
#       - "1313:1313"
#     volumes:
#       - .:/src
